// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3JJhF07WBDICP4ecaB4uo325ZndW679M',
    appId: '1:824544394232:web:a8bf5818440e382be0b40d',
    messagingSenderId: '824544394232',
    projectId: 'pushflutter-9179e',
    authDomain: 'pushflutter-9179e.firebaseapp.com',
    storageBucket: 'pushflutter-9179e.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_tWOVcYGQzyVX3X1MKJC5O3DiKYxPKIQ',
    appId: '1:824544394232:ios:f10ac693135a30c3e0b40d',
    messagingSenderId: '824544394232',
    projectId: 'pushflutter-9179e',
    storageBucket: 'pushflutter-9179e.appspot.com',
    iosBundleId: 'com.example.pushtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3JJhF07WBDICP4ecaB4uo325ZndW679M',
    appId: '1:824544394232:web:80dd551105321e97e0b40d',
    messagingSenderId: '824544394232',
    projectId: 'pushflutter-9179e',
    authDomain: 'pushflutter-9179e.firebaseapp.com',
    storageBucket: 'pushflutter-9179e.appspot.com',
  );
}
